### ISSUE TITLE
EDU: Fix colors on login form

### ISSUE THREAD

**Issue by ziobron** [coders-school/site#34]
Maybe darker background? #363232 or #272625?
"Remember me" text is not visible now

<img width="859" alt="Zrzut ekranu 2020-04-29 o 14 05 43" src="https://user-images.githubusercontent.com/4595135/80594053-9a45ac80-8a22-11ea-938c-d2026d4eb29a.png">

**Comment by kawapa** [comment]
#363232 is nice

![Screenshot from 2020-04-29 23-19-54](https://user-images.githubusercontent.com/30127736/80648187-07336380-8a70-11ea-8b0c-e1b08212df83.png)

**Comment by ziobron** [comment]
Looks good :)
Please use variables in CSS instead of raw colors. They are defined in the begining of additional CSS:
```css
:root {
  --major: #cf802a;
	--back: #363232;
	--front: #fff;
	--minor: #c9c9d3;
	--menu: #272625;
	--accent: #8B3536;
}
```
